### ISSUE TITLE
Please update link to pipeline.yml

### ISSUE THREAD

**Issue by amuessig** [cloudfoundry-incubator/bosh-disaster-recovery-acceptance-tests#4]
The link to the `pipeline.yml` (https://github.com/cloudfoundry-incubator/backup-and-restore-ci/blob/master/ci/b-drats/pipeline.yml) is not valid anymore. Please update it with a working version.

Thanks

P.S. Is this project still in development or is it canceled?

**Comment by MirahImage** [comment]
The correct location is here https://github.com/cloudfoundry-incubator/backup-and-restore-ci/blob/master/pipelines/b-drats/pipeline.yml

**Comment by amuessig** [comment]
Thanks!
